import { EmbedBuilder } from "discord.js";
import { getRandomFooter } from "../../utils/raphael.js";

export default {
  name: "invite",
  description: "Get an invite link to a specific server (Owner only)",
  ownerOnly: true,
  usage: "<server_name_or_id>",

  async execute(message, args) {
    try {
      if (!args.length) {
        return message.reply({
          embeds: [
            new EmbedBuilder()
              .setColor(message.client.color.red)
              .setTitle("▸ Invalid Usage")
              .setDescription(
                "Please provide a server name or ID.\n\n`!invite <server_name_or_id>`",
              )
              .setFooter({ text: getRandomFooter() }),
          ],
        });
      }

      const searchTerm = args.join(" ").toLowerCase();
      const client = message.client;
      const guilds = client.guilds.cache;

      // Search by name or ID
      let targetGuild = guilds.find((g) =>
        g.name.toLowerCase().includes(searchTerm),
      );
      if (!targetGuild && /^\d+$/.test(searchTerm)) {
        targetGuild = guilds.get(searchTerm);
      }

      if (!targetGuild) {
        return message.reply({
          embeds: [
            new EmbedBuilder()
              .setColor(message.client.color.red)
              .setTitle("▸ Server Not Found")
              .setDescription(
                `Could not find a server matching **${searchTerm}**, Master.`,
              )
              .setFooter({ text: getRandomFooter() }),
          ],
        });
      }

      // Try to create an invite
      const channel = targetGuild.channels.cache.find(
        (ch) =>
          ch.isTextBased() &&
          ch
            .permissionsFor(targetGuild.members.me)
            .has(["CreateInstantInvite", "ViewChannel"]),
      );

      if (!channel) {
        return message.reply({
          embeds: [
            new EmbedBuilder()
              .setColor(message.client.color.red)
              .setTitle("▸ Cannot Create Invite")
              .setDescription(
                `I don't have permission to create invites in **${targetGuild.name}**, Master.\n\nEnsure I have the **Create Invite** permission.`,
              )
              .setFooter({ text: getRandomFooter() }),
          ],
        });
      }

      const invite = await channel.createInvite({
        maxAge: 86400, // 24 hours
        maxUses: 0,
        reason: "Generated by owner via invite command",
      });

      return message.reply({
        embeds: [
          new EmbedBuilder()
            .setColor(message.client.color.main)
            .setTitle(`▸ Invite to ${targetGuild.name}`)
            .addFields(
              { name: "◈ Server", value: targetGuild.name, inline: true },
              {
                name: "◆ Members",
                value: targetGuild.memberCount.toString(),
                inline: true,
              },
              {
                name: "▸ Invite Link",
                value: `[Join Server](${invite.url})`,
                inline: false,
              },
              { name: "◉ Expires", value: "In 24 hours", inline: true },
              { name: "◎ Uses", value: "Unlimited", inline: true },
            )
            .setThumbnail(targetGuild.iconURL({ size: 256 }))
            .setFooter({ text: getRandomFooter() })
            .setTimestamp(),
        ],
      });
    } catch (error) {
      console.error("[INVITE] Error:", error);
      return message.reply({
        embeds: [
          new EmbedBuilder()
            .setColor(message.client.color.red)
            .setTitle("▸ Error")
            .setDescription(
              `An error occurred while generating the invite:\n\`\`\`${error.message}\`\`\``,
            )
            .setFooter({ text: getRandomFooter() }),
        ],
      });
    }
  },
};
