/**
 * Playing-card emojis, uploaded as application emojis named like A_spades,
 * 10_hearts and card_back (images generated by `npm run cards`). Looked up by
 * name, so no emoji IDs need to be copied into config.
 */

import logger from './logger.js';

// Re-fetch periodically so newly uploaded emojis show up without a restart
const CACHE_TTL = 5 * 60 * 1000;

const SUIT_NAMES = { '♠️': 'spades', '♥️': 'hearts', '♦️': 'diamonds', '♣️': 'clubs' };

let cache = new Map();
let cachedAt = 0;

export async function getCardEmojis(client) {
  if (Date.now() - cachedAt < CACHE_TTL) return cache;
  try {
    const emojis = await client.application.emojis.fetch();
    cache = new Map(emojis.map((emoji) => [emoji.name, emoji.toString()]));
    cachedAt = Date.now();
  } catch (error) {
    // Keep the previous map (or text fallbacks) and retry on the next game
    logger.warn('Failed to fetch card emojis', error);
  }
  return cache;
}

/**
 * Emoji for a { value, suit } card: the flip animation for a card just dealt
 * (`flip`), otherwise the static face, so only new cards flip when a message is
 * edited. Falls back to the other version, then to a text card if neither is uploaded.
 */
export function cardEmoji(card, emojis, flip = false) {
  const name = `${card.value}_${SUIT_NAMES[card.suit]}`;
  const [preferred, fallback] = flip ? [name, `${name}_static`] : [`${name}_static`, name];
  return emojis.get(preferred) ?? emojis.get(fallback) ?? `\`${card.value}${card.suit}\``;
}

export function cardBackEmoji(emojis) {
  return emojis.get('card_back') ?? '🎴';
}
